### ISSUE TITLE
GetSystemTimePreciseAsFileTime win32 API is not available on Win7?

### ISSUE THREAD

**Issue by edwinyzh** [grijjy/DelphiDuktape#1]
First, congrats for the new amazing project!

And here is an issue report:
I've successfully compiled the `DuktapeHighLevel` demo, upon starting up, it gives the `Cannot locate GetSystemTimePreciseAsFileTime in kerner.dll' error.

According to MSDN, GetSystemTimePreciseAsFileTime  needs at least Windows 8?

**Comment by erikvanbilsen** [comment]
Thanks! Looks like the Duktape DLL uses GetSystemTimePreciseAsFileTime unless disabled in the config script. I disabled this option and recompiled the DLLs. Let me know if there are any other problems with Windows 7, since I cannot test that here.
